apiVersion: v1
kind: ConfigMap
metadata:
  name: tom-config
data:
  tomcat-user: |
    <tomcat-users xmlns="http://tomcat.apache.org/xml"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
                  version="1.0">

      <user username="digi" password="digi" roles="manager-gui,admin-gui"/>
    </tomcat-users>