apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: dev
spec:
  limits:
  - default:
      cpu: 400m
      memory: 512Mi
    defaultRequest:
      cpu: 400m
      memory: 256Mi
    max:
      cpu: 400m
      memory: 512Mi
    min:
      cpu: 200m
      memory: 256Mi
    type: Container
  
