apiVersion: v1
kind: Pod
metadata:
  name: probe
  labels:
    app: web
spec:
  containers:
  - name: probe
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args: ["liveness"]
    ports:
      - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
          - name: X-Custom-Header
            value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
