apiVersion: apps/v1
kind: Deployment
metadata:
  name: tom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tom
  template:
    metadata:
      labels:
        app: tom
    spec:
      containers:
      - name: tom-container
        image: rahulkumar9536/project1:2
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
